MAIN:
  PRINT "WHAT IS YOUR NAME?"
  INPUT NAME$
  LET GREETING$ = "HELLO, " + NAME$
  PRINT GREETING$
  INPUT N
  LET I = 0

LOOP:
  PRINT I
  LET I = I + 1
  IF I < N THEN GOTO LOOP ELSE PRINT "COUNT COMPLETE"

DONE:
  PRINT "DONE"
  END
